name: flutter_prime
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.4
  flutter_svg: ^2.0.4
  lottie: ^2.3.1
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  country_picker: ^2.0.11
  circular_countdown_timer: ^0.2.3
  intl: ^0.18.1
  pin_code_fields: ^7.3.0
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.14.6
  share_plus: ^4.0.6
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  octo_image: ^2.0.0
  bottom_navy_bar: ^6.0.0
  simple_animations: ^4.2.0
  dotted_border: ^2.0.0+2
  cached_network_image: ^3.3.0
  firebase_messaging: ^12.0.3
  firebase_analytics: ^9.3.2
  firebase_core: ^1.21.0
  firebase_core_platform_interface: 4.5.1
  animated_floating_buttons: ^0.0.2
  file_picker: ^5.2.4
  awesome_dialog: ^3.0.2
  connectivity_plus: ^2.3.6+1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  gallery_saver: ^2.3.2
  dio: ^5.0.1
  image_picker: ^0.8.6+1
  flutter_local_notifications: ^13.0.0
  permission_handler: ^10.2.0
  image_gallery_saver: ^2.0.3
  zoom_tap_animation: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/img/
    - assets/icons/
    - assets/animation/
  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Bold.ttf
        - asset: assets/fonts/Rajdhani-Light.ttf
        - asset: assets/fonts/Rajdhani-Medium.ttf
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-SemiBold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf



